apiVersion: v1
kind: ConfigMap
metadata:
  name: swei99wf-config
  namespace: namespace-workflow-1757435239997
  labels:
    app.kubernetes.io/name: swei99wf
    kubernetes.azure.com/generator: devhub
data: