apiVersion: v1
kind: ConfigMap
metadata:
  name: swei-725-config
  namespace: namespace-workflow-1753480316252
  labels:
    app.kubernetes.io/name: swei-725
    kubernetes.azure.com/generator: devhub
data: