apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swei819
  labels:
    app.kubernetes.io/name: swei819
    app.kubernetes.io/part-of: swei819-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: swei819