apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swei724
  labels:
    app.kubernetes.io/name: swei724
    app.kubernetes.io/part-of: swei724-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: swei724