apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swei-725
  labels:
    app.kubernetes.io/name: swei-725
    app.kubernetes.io/part-of: swei-725-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: swei-725