apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sweitestv2
  labels:
    app.kubernetes.io/name: sweitestv2
    app.kubernetes.io/part-of: sweitestv2-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sweitestv2