apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sweinew730
  labels:
    app.kubernetes.io/name: sweinew730
    app.kubernetes.io/part-of: sweinew730-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sweinew730