apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swei829wf
  labels:
    app.kubernetes.io/name: swei829wf
    app.kubernetes.io/part-of: swei829wf-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: swei829wf