apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sweitest730
  labels:
    app.kubernetes.io/name: sweitest730
    app.kubernetes.io/part-of: sweitest730-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sweitest730