apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: devhub-test725
  labels:
    app.kubernetes.io/name: devhub-test725
    app.kubernetes.io/part-of: devhub-test725-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: devhub-test725