apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sweinew724v2
  labels:
    app.kubernetes.io/name: sweinew724v2
    app.kubernetes.io/part-of: sweinew724v2-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sweinew724v2