apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swei-dev-729
  labels:
    app.kubernetes.io/name: swei-dev-729
    app.kubernetes.io/part-of: swei-dev-729-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: swei-dev-729