apiVersion: v1
kind: Service
metadata:
  name: swei724
  namespace: namespace-workflow-1753393029984
  labels:
    app.kubernetes.io/name: swei724
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: swei724
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80