apiVersion: v1
kind: Service
metadata:
  name: swei819
  namespace: namespace-workflow-1755628120340
  labels:
    app.kubernetes.io/name: swei819
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: swei819
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80