apiVersion: v1
kind: Service
metadata:
  name: swei99wf
  namespace: namespace-workflow-1757435239997
  labels:
    app.kubernetes.io/name: swei99wf
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: swei99wf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80