apiVersion: v1
kind: Service
metadata:
  name: sweinew730
  namespace: namespace-workflow-1753916316474
  labels:
    app.kubernetes.io/name: sweinew730
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: sweinew730
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80