apiVersion: v1
kind: Service
metadata:
  name: swei829wf
  namespace: namespace-workflow-1756492821341
  labels:
    app.kubernetes.io/name: swei829wf
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: swei829wf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80