apiVersion: v1
kind: Service
metadata:
  name: swei-725
  namespace: namespace-workflow-1753480316252
  labels:
    app.kubernetes.io/name: swei-725
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: swei-725
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80