apiVersion: v1
kind: Service
metadata:
  name: sweitest730
  namespace: namespace-workflow-1753912861677
  labels:
    app.kubernetes.io/name: sweitest730
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: sweitest730
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80