apiVersion: v1
kind: Service
metadata:
  name: sweinew724v2
  namespace: namespace-workflow-1753393748139
  labels:
    app.kubernetes.io/name: sweinew724v2
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: sweinew724v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80